ServerName localhost

Listen 80

# --- Core modules (essentiels) ---
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule rewrite_module modules/mod_rewrite.so

# --- Proxy vers PHP-FPM (drupalpro_php:9000) ---
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

# Logs vers stdout/stderr (Docker)
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

# Drupal docroot = /web (recommended-project)
DocumentRoot "/var/www/html/web"
DirectoryIndex index.php index.html

<Directory "/var/www/html/web">
  AllowOverride All
  Require all granted
</Directory>

# Envoyer les .php vers PHP-FPM
<FilesMatch \.php$>
  SetHandler "proxy:fcgi://php:9000"
</FilesMatch>