ServerName localhost

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule headers_module modules/mod_headers.so

<VirtualHost *:80>
  DocumentRoot "/var/www/html/web"

  <Directory "/var/www/html/web">
    AllowOverride All
    Require all granted
  </Directory>

  # PHP-FPM via container php:9000
  <FilesMatch \.php$>
    SetHandler "proxy:fcgi://php:9000"
  </FilesMatch>
</VirtualHost>